### ISSUE TITLE
Google Analytics

### ISSUE THREAD

**Issue by gregtatum** [alexbelyeu/shooterCoaster#1]
Would you remind removing the google analytics tag? It's sending usage data to my own site:

https://github.com/alexbelyeu/shooterCoaster/blob/gh-pages/index.html#L20-L29

**Comment by alexbelyeu** [comment]
Sorry about that! That shows how little I knew about what I was doing back then 😅. Thanks for providing the building blocks for the game, I wouldn't be a Software Engineer today if it wasn't for them.

**Comment by gregtatum** [comment]
Yeah, no worries!

> I wouldn't be a Software Engineer today if it wasn't for them.

Wow, all the feels this morning. I'm glad it was helpful! Best of luck.
